In [4]:
# important imports 

import numpy as np # for linear algebra and matrix & vector computations
import pandas as pd # for data processing and reading data
from matplotlib import pyplot as plt # for displaying plots and images
import os

In [6]:
# getting data from csv file as a pandas dataframe

cwd = os.getcwd()
data_dir_path = os.path.join(cwd, "digit-recognizer")
data_file_path = os.path.join(data_dir_path, "train.csv")
data = pd.read_csv(data_file_path)

In [8]:
data.head()
# here each row correspods to one image data with columns corresponding to data for a pixel in the image

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
# data in form of a numpy array
data = np.array(data)

# splitting data in dev and training sets due to risk of overfitting
m, n = data.shape
np.random.shuffle(data)

TypeError: 'tuple' object is not callable